source "https://rubygems.org"
gemspec

gem 'jekyll-compose', group: [:jekyll_plugins]
gem "webrick"
gem "github-pages", group: :jekyll_plugins
gem "jekyll", "~> 3.9"
# gem 'not-pure-poole'
gem 'jekyll-remote-theme'
